#!/bin/sh
#
# @name CNU HELI1 Helicopter (Tail Servo)
#
# @type Helicopter
# @class Copter
#
# @board px4_fmu-v2 exclude
# @board bitcraze_crazyflie exclude
#

. ${R}etc/init.d/rc.heli_defaults

# Disable PID gains for initial setup. These should be enabled after setting the FF gain.
# P is expected to be lower than FF.
param set-default MC_ROLLRATE_P 0
param set-default MC_ROLLRATE_I 0
param set-default MC_ROLLRATE_D 0
param set-default MC_ROLLRATE_FF 0.1
param set-default MC_PITCHRATE_P 0
param set-default MC_PITCHRATE_I 0
param set-default MC_PITCHRATE_D 0
param set-default MC_PITCHRATE_FF 0.1

param set-default COM_SPOOLUP_TIME 0

param set-default CA_METHOD 2
param set-default CA_AIRFRAME 11

param set-default CA_HELI_PITCH_C0 -0.05
param set-default CA_HELI_PITCH_C1 0
param set-default CA_HELI_PITCH_C2 0.07
param set-default CA_HELI_PITCH_C3 0.14
param set-default CA_HELI_PITCH_C4 0.21

param set-default CA_HELI_THR_C0 0.6
param set-default CA_HELI_THR_C1 0.6
param set-default CA_HELI_THR_C2 0.6
param set-default CA_HELI_THR_C3 0.6
param set-default CA_HELI_THR_C4 0.6

param set-default CA_HELI_YAW_CCW 0
param set-default CA_HELI_YAW_CP_O 0
param set-default CA_HELI_YAW_CP_S 0.2
param set-default CA_HELI_YAW_TH_S 0.18

param set-default CA_SP0_COUNT 3
param set-default CA_SP0_ANG0 60
param set-default CA_SP0_ANG1 180
param set-default CA_SP0_ANG2 300
param set-default CA_SP0_ANG3 0
param set-default CA_SP0_ARM_L0 1
param set-default CA_SP0_ARM_L1 1
param set-default CA_SP0_ARM_L2 1
param set-default CA_SP0_ARM_L3 1
param set-default CA_SV_CS0_TRIM 0.05
param set-default CA_SV_CS1_TRIM 0.2
param set-default CA_SV_CS2_TRIM -0.15
param set-default CA_SV_CS3_TRIM 0

param set-default PWM_MAIN_FUNC1 101
param set-default PWM_MAIN_FUNC2 0
param set-default PWM_MAIN_FUNC3 201
param set-default PWM_MAIN_FUNC4 202
param set-default PWM_MAIN_FUNC5 203
param set-default PWM_MAIN_FUNC6 204
param set-default PWM_MAIN_FUNC7 0
param set-default PWM_MAIN_FUNC8 0

param set-default PWM_MAIN_DIS1 1000
param set-default PWM_MAIN_DIS2 1000
param set-default PWM_MAIN_DIS3 1500
param set-default PWM_MAIN_DIS4 1500
param set-default PWM_MAIN_DIS5 1500
param set-default PWM_MAIN_DIS6 1500
param set-default PWM_MAIN_DIS7 1000
param set-default PWM_MAIN_DIS8 1000
param set-default PWM_MAIN_MIN1 1100
param set-default PWM_MAIN_MIN2 1000
param set-default PWM_MAIN_MIN3 1000
param set-default PWM_MAIN_MIN4 1000
param set-default PWM_MAIN_MIN5 1000
param set-default PWM_MAIN_MIN6 1000
param set-default PWM_MAIN_MIN7 1000
param set-default PWM_MAIN_MIN8 1000
param set-default PWM_MAIN_MAX1 1900
param set-default PWM_MAIN_MAX2 2000
param set-default PWM_MAIN_MAX3 2000
param set-default PWM_MAIN_MAX4 2000
param set-default PWM_MAIN_MAX5 2000
param set-default PWM_MAIN_MAX6 2000
param set-default PWM_MAIN_MAX7 2000
param set-default PWM_MAIN_MAX8 2000
param set-default PWM_MAIN_REV 36
param set-default PWM_MAIN_TIM0 400
param set-default PWM_MAIN_TIM1 50
param set-default PWM_MAIN_TIM2 50

param set-default SDLOG_PROFILE 9

param set-default SYS_ID_EN 0
param set-default SYS_ID_AXIS 1
param set-default SYS_ID_AMP 0.1
param set-default SYS_ID_INTERV 10
param set-default SYS_ID_OME_MIN 0.3
param set-default SYS_ID_OME_MAX 12
param set-default SYS_ID_T_REC 10
param set-default SYS_ID_Y_TRIM 0
param set-default SYS_ID_RC_MODE_CH 0
param set-default SYS_ID_RC_AXIS_CH 0
